title: Your awesome title
author: chaitany arora
email: arorachaitany15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is man is Legendary. You surely wanna meet this guy. Barney 2006

# social links
twitter_username: chaitanyarora1 # DO NOT include the @ character, or else the build will fail!
github_username:  chaitanyarora # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
